###################################
# WRF-Hydro Development docker
# Purpose:
#   1) Compile code on the host system (non-interactive mode)
##     Usage
#   2) Run code on the host system     (non-interactive mode)
#   3) Interactive use. 
#   
# Authors: Tony Castronova, James McCreight
# Email:  acastronova@cuahsi.org, jamesmcc@ucar.edu
# Date:  8.29.2017, 9.15.2017
###################################

FROM ubuntu:16.04
MAINTAINER jamesmcc@ucar.edu

####################################
########## ROOT USER  ##############
####################################
USER root

###################################
## System-wide updates
RUN apt-get update


####################################
## WRF-Hydro dependencies
RUN apt-get install -yq --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    vim \ 
    libhdf5-dev \
    gfortran \
    m4 \
    make\ 
    libswitch-perl \ 
    mpich \
    libopenmpi-dev \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install netcdf-C
RUN wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.1.tar.gz -P /tmp  
RUN tar -xf /tmp/netcdf-4.4.1.1.tar.gz -C /tmp
ENV H5DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial
ENV NCDIR=/usr/local
RUN cd /tmp/netcdf-4.4.1.1 && CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib ./configure --prefix=/usr/local
RUN cd /tmp/netcdf-4.4.1.1 && make
RUN cd /tmp/netcdf-4.4.1.1 && make install

# install netcdf-Fortran
RUN wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz
RUN tar -xf netcdf-fortran-4.4.4.tar.gz -C /tmp
ENV NFDIR=/usr/local
ENV LD_LIBRARY_PATH=${NCDIR}/lib
RUN cd /tmp/netcdf-fortran-4.4.4/ && CPPFLAGS=-I${NCDIR}/include LDFLAGS=-L${NCDIR}/lib ./configure --prefix=${NFDIR}
RUN cd /tmp/netcdf-fortran-4.4.4 && make
RUN cd /tmp/netcdf-fortran-4.4.4 && make install


###################################
## gosu dependencies
## gosu is to enable compiling and running as user on host file system
## JLM: does not seem to solve strange compilation behavior on mounted drive
#RUN apt-get update && apt-get -y --no-install-recommends install \
#    curl
#RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
#RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
#    && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/do#wnload/1.4/gosu-$(dpkg --print-architecture).asc" \
#    && gpg --verify /usr/local/bin/gosu.asc \
#    && rm /usr/local/bin/gosu.asc \
#    && chmod +x /usr/local/bin/gosu
#COPY entrypoint_gosu.sh /usr/local/bin/entrypoint_gosu.sh
#ENTRYPOINT ["/usr/local/bin/entrypoint_gosu.sh"]


###################################
## wrf_hydro_tools dependencies
RUN apt-get update && apt-get -y --no-install-recommends install \
    git

###################################
## create joedocker user
RUN useradd -ms /bin/bash joedocker
RUN usermod -aG sudo joedocker
ENV NETCDF=/usr/local

###################################
## wrf-hydro development docker interface script
COPY ./interface.sh /.

####################################
######### joedocker user ###########
####################################
USER joedocker
RUN cp /interface.sh ~/.
RUN cd $HOME
ENTRYPOINT ["/interface.sh"]
CMD ["interactive"]