sudo: required
dist: trusty
services:
  - docker

install: []
before_script: []
script:
  - travis_wait 30 cd dev/base/; bash build.sh; cd - #Long running build add in travis wait
  - echo "-------------------------"; echo "building dev:conda"; cd dev/conda/; bash build.sh; cd -
  - echo "-------------------------"; echo "building domains:croton_NY"; cd domains/croton_NY/; bash build.sh; cd -
  - echo "-------------------------"; echo "building training:latest";cd training; bash build.sh; cd -
#  - travis_wait 30 bash build_all.sh

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script:
    - docker push wrfhydro/dev:base
    - docker push wrfhydro/dev:conda
    - docker push wrfhydro/domains:croton_NY
    - docker push wrfhydro/training
