sudo: required
dist: trusty
services:
  - docker

install: []
before_script: []
script:
  - cd -;
  - travis_wait 30 cd $TRAVIS_BUILD_DIR/dev/base/; bash build.sh; #Long running build add in travis wait
  - echo "building dev:conda"; cd $TRAVIS_BUILD_DIR/dev/conda/; bash build.sh;
  - echo "building domains:croton_NY"; cd $TRAVIS_BUILD_DIR/domains/croton_NY/; bash build.sh;
  - echo "building training:latest"; cd $TRAVIS_BUILD_DIR/training; bash build.sh; 
#  - travis_wait 30 bash build_all.sh

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script:
    - docker push wrfhydro/dev:base
    - docker push wrfhydro/dev:conda
    - docker push wrfhydro/domains:croton_NY
    - docker push wrfhydro/training
