sudo: required
dist: trusty
services:
  - docker

install: []
before_script: []
script:
  - cd dev/base/; bash build.sh; cd -
  - cd dev/conda/; bash build.sh; cd -
  - cd domains/croton_NY/; bash build.sh; cd -
  - cd training; bash build.sh; cd -
#  - travis_wait 30 bash build_all.sh

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script:
    - docker push wrfhydro/dev:base
    - docker push wrfhydro/dev:conda
    - docker push wrfhydro/domains:croton_NY
    - docker push wrfhydro/training
