FROM alpine:latest
MAINTAINER James McCreight <jamesmcc@ucar.edu>
COPY domain_dart/ /home/docker/domain_dart/
RUN chmod -R 777 /home/docker/domain_dart/matthew_channel-only

VOLUME /home/docker/domain_dart/matthew_channel-only

#ENTRYPOINT ["dummy/entry/point"]
