###################################
# Purpose: Set a ubuntu base distribution
#           for subsequent docker builds.
# Author : James McCreight <jamesmcc -at- ucar.edu>
# Date   : 11.1.17
###################################

#FROM ubuntu:16.04
FROM phusion/baseimage

MAINTAINER jamesmcc

####################################
########## ROOT USER  ##############
####################################
USER root