FROM scratch
MAINTAINER Joe Mills <jmills@ucar.edu>
COPY croton_NY/ /home/docker/domain/croton_NY
COPY readme.txt /home/docker/domain/croton_NY/
COPY Croton_usgsObs_01374559.csv /home/docker/domain/croton_NY/
VOLUME /home/docker/domain/croton_NY

ENTRYPOINT ["dummy/entry/point"]
